DATA_FRACTION = 0.05
# BATCH_SIZE = 16
# EMBED_SIZE = 256
# HIDDEN_SIZE = 256
# FEATURE_DIM = 2048
# VOCAB_FREQ_THRESHOLD = 2
# # VOCAB_SIZE = 5000
# LEARNING_RATE = 1e-3
# FINETUNING_LR = 1e-4
# NUM_EPOCHS = 10
SAMPLE_CNT_BLEU = 10

CHECKPOINT_PATH = "checkpoints/model.pth"
VOCAB_PATH = "checkpoints/vocab.json"

BATCH_SIZE = 16
EMBED_SIZE = 64
HIDDEN_SIZE = 64
FEATURE_DIM = 2048
VOCAB_FREQ_THRESHOLD = 2
# VOCAB_SIZE = 5000
LEARNING_RATE = 1e-3
FINETUNING_LR = 1e-4
NUM_EPOCHS = 1